name: medical_devices
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_translate: ^4.0.3
  flutter_localizations:
    sdk: flutter
  flutter_settings_screens: ^0.2.2+1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bl_1500.png
    - assets/images/bpm_100.png
    - assets/images/bpm_200w.png
    - assets/images/bt_125.jpeg
    - assets/images/it_45b.png
    - assets/images/ol_750.png
    - assets/i18n/en.json
    - assets/i18n/es.json






